services:

  api:
    container_name: api
    build: .
    environment:
      - SQLITE_HOST=sqlite://sqlite.db
    command: python -m uvicorn --host 0.0.0.0 --port 8000 app.main:app
    volumes:
      - .:/code
      - sqlite_data:/db_data/
    ports:
      - 8000:8000

volumes:
  sqlite_data:
